# Exported from:        http://mateas-mac:5516/
# Release version:      10.0.0-20210203-123974
# Date created:         Wed Apr 07 10:08:20 CEST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: test ENG-4724
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.mySampleVar
    value: sample
