# Exported from:        http://MacBook-Pro.local:5516/
# Release version:      10.0.0-20210203-123974
# Date created:         Wed Jun 02 11:32:02 CEST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: sdlm
spec:
- template: templ1
  scheduledStartDate: 2021-06-02T09:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
